export const NIGHTCAP_QUESTIONS: string[] = [
  // Gratitude & Appreciation (1-19)
  "What's one thing I did today that made your life easier?",
  "What's a small moment from today you want to remember?",
  "What's something about our life together you felt grateful for today?",
  "When did you feel most loved today?",
  "What's a quality in me you were thankful for today?",
  "What's something good that happened today that you almost didn't notice?",
  "What's one thing about our home that made you happy today?",
  "Who outside our family did something kind for you today?",
  "What's a simple pleasure you enjoyed today?",
  "What's something about our kids that made you smile today?",
  "What's something you appreciate about me today?",
  "What's something I did recently that meant a lot to you?",
  "What's one quality you admire in me?",
  "What's something about our relationship you're grateful for?",
  "What's a memory of us that makes you smile?",
  "What's something small I do that you love?",
  "What's something about our life together that feels special?",
  "What's something we do well as a team?",
  "What makes you proud of us?",
  // Daily Life & Reflection (20-29)
  "What was the best part of your day?",
  "What was the hardest part of your day?",
  "What made you smile today?",
  "What drained your energy today?",
  "Did anything surprise you today?",
  "What's something you learned today?",
  "What moment from today do you want to remember?",
  "What was one small win today?",
  "What stressed you out today?",
  "What are you grateful for today?",
  // Emotional Check-In (30-47)
  "On a scale of 1–10, how full is your emotional tank right now?",
  "How are you feeling right now, really?",
  "What emotion did you feel most today?",
  "Did anything today make you feel especially loved?",
  "Did anything today make you feel unseen?",
  "What do you need more of from me this week?",
  "What do you need less of from me this week?",
  "What would help you feel more supported this week?",
  "What has been on your mind lately?",
  "Is there something you've been carrying alone?",
  "What would make tomorrow feel lighter?",
  "What's weighing on you that I can help carry?",
  "Is there anything I said or did recently that stung, even if I didn't mean it?",
  "What's one thing on your to-do list that's been silently stressing you out?",
  "Are we spending enough time together that actually feels connected, not just logistical?",
  "Is there a conversation we've been avoiding?",
  "How are you feeling about our balance of work, family, and personal time?",
  "What's one area of your life where you feel like you're winning right now?",
  // Dreams & the Future (48-67)
  "If money were no object, what would our ideal Saturday look like five years from now?",
  "What's a skill you'd love to learn together?",
  "Where's one place you'd love to take our family someday?",
  "What's a tradition you want our kids to remember us for?",
  "If we had a free year with no obligations, how would you spend the first month?",
  "What does 'financial freedom' actually feel like to you — not the number, the feeling?",
  "What's a wild idea you've been quietly thinking about but haven't said out loud?",
  "What kind of old couple do you want us to be?",
  "What's one thing you hope our kids learn from watching our marriage?",
  "If we could design our perfect home from scratch, what's the one non-negotiable room or feature?",
  "What's something you're excited about right now?",
  "What's something you want to try this year?",
  "Where would you love to travel next?",
  "What's something you want to learn?",
  "What's a dream you've had for a long time?",
  "What would your ideal day look like?",
  "What's a goal you're quietly working toward?",
  "What kind of life do you want us to build?",
  "What adventure should we plan?",
  "What would make this year feel meaningful?",
  // Memories & Nostalgia (68-85)
  "What's your favorite memory of us from before we had kids?",
  "When did you first know you wanted to marry me?",
  "What's a hard season we went through that actually made us stronger?",
  "What's a trip we took that you'd love to do again?",
  "What's the funniest thing that's ever happened to us?",
  "What's a moment where I totally surprised you?",
  "What's your favorite photo of us, and why?",
  "What's something from our early relationship you miss?",
  "What's a lesson you learned from your parents' marriage — good or bad?",
  "What's a gift I gave you that meant more than I probably realized?",
  "What's something about when we first met that you remember?",
  "What's a moment we handled something well together?",
  "What trip together stands out most?",
  "What moment made you realize you loved me?",
  "What's a random memory you have about us?",
  "What's a moment you felt really proud of us?",
  "What's a memory that still makes you laugh?",
  "What's something we should recreate from the past?",
  // Parenting (86-95)
  "What's one thing our toddler did today that amazed you?",
  "What's the hardest part of parenting right now that you don't talk about enough?",
  "How are you feeling about baby number two arriving?",
  "What kind of dad/mom did you imagine you'd be vs. who you actually are?",
  "What's one parenting value we're aligned on that you're proud of?",
  "Is there a parenting approach we need to get on the same page about?",
  "What's one thing your parents did that you definitely want to replicate?",
  "What's one thing your parents did that you definitely want to avoid?",
  "What age of our kid are you most excited to experience?",
  "How can I better support you during the tough parenting moments?",
  // Fun & Hypotheticals (96-115)
  "If you could have dinner with anyone alive, who would it be and what would you ask?",
  "What's a movie or show you could rewatch forever?",
  "If we switched lives for a day, what would surprise you most about my routine?",
  "What's the most useless talent you wish you had?",
  "If you could instantly be fluent in any language, which one?",
  "What's a food you pretended to like when we started dating?",
  "If our family had a theme song, what would it be?",
  "What's the most adventurous thing you'd do if you knew you couldn't fail?",
  "If you could relive one day of your life, which would it be?",
  "What would your autobiography be titled?",
  "What's something that made you laugh today?",
  "If today had a title, what would it be?",
  "What random thing did you think about today?",
  "What's something weird you've been curious about lately?",
  "If today were a movie, what genre would it be?",
  "What's a small thing that makes life better lately?",
  "What song has been stuck in your head?",
  "What's something funny you saw today?",
  "What's a silly thing we should do soon?",
  "If we had tomorrow off, what would we do?",
  // Spiritual & Values (116-132)
  "What's something from the scriptures that's been on your mind lately?",
  "When did you last feel the Spirit strongly, and what was happening?",
  "What's a spiritual question you're still working through?",
  "How can I better support your personal scripture study and prayer?",
  "What's a gospel principle that means more to you now than it did five years ago?",
  "What do you hope our kids understand about faith by the time they leave home?",
  "What's a talk or lesson that changed how you see something?",
  "Is there a calling or service opportunity you'd love to have someday?",
  "How are you feeling about our family's Sabbath day right now?",
  "What's a moment where you felt God was clearly guiding our family?",
  "What does love mean to you right now?",
  "What helps you feel safe in a relationship?",
  "What does a good life look like to you?",
  "What do you want to be remembered for?",
  "What kind of parent/partner/person do you want to be?",
  "What values matter most to you right now?",
  "What gives your life meaning lately?",
  // Personal Growth (133-152)
  "What's a personal weakness you've been working on that nobody notices?",
  "What's something you've gotten measurably better at this year?",
  "What's a book, podcast, or idea that recently shifted your thinking?",
  "What's one habit you wish you could lock in permanently?",
  "Where do you feel stuck right now, and what would getting unstuck look like?",
  "What's a fear that's quietly holding you back from something?",
  "What would you do differently if you cared zero percent about what people thought?",
  "What's a compliment someone gave you that you're still thinking about?",
  "What's the hardest feedback you've ever received that turned out to be right?",
  "What's one thing you want to be known for at the end of your life?",
  "What's something you're proud of about yourself?",
  "What's something you want to improve?",
  "What challenge are you currently facing?",
  "What motivates you lately?",
  "What drains you lately?",
  "What helps you recharge?",
  "What's something you're afraid of right now?",
  "What's something you've been thinking deeply about?",
  "What's something you want to understand better?",
  "What's a lesson life has been teaching you lately?",
  // Us as a Team (153-172)
  "What's one thing we do really well together as a team?",
  "Where do we have the most friction in our daily routine, and how could we fix it?",
  "What's a decision we made together that you're really proud of?",
  "How are we doing on dividing the mental load at home?",
  "What's one weekly rhythm or routine we should start?",
  "Is there something you handle alone that you wish I'd step into more?",
  "What's the best way for us to make a big decision together?",
  "When we disagree, what do I do that actually helps resolve things?",
  "When we disagree, what do I do that makes things worse?",
  "What's one investment in our relationship that would pay the biggest dividends right now?",
  "What's something we've improved in our relationship?",
  "What's something we could work on together?",
  "When do you feel most connected to me?",
  "When do you feel most distant?",
  "What's one habit we could build together?",
  "What would make our evenings better?",
  "What's something we should do more often?",
  "What's something we should stop doing?",
  "What would make you feel more loved this month?",
  "What's one way we could support each other better?",
  // Intimacy & Connection (173-185)
  "What makes you feel most emotionally close to me?",
  "When this week did you feel most disconnected from me?",
  "What's your love language this season — has it shifted at all?",
  "What's one small daily gesture that would mean the world to you?",
  "What's a date idea you've been wanting to try?",
  "Do you feel like I really see you right now, or are we running on autopilot?",
  "What can I do to make you feel more desired?",
  "What's something I used to do when we were dating that you'd love me to bring back?",
  "What's one non-physical way I can show you love this week?",
  "If you could describe the best version of 'us' in one sentence, what would it be?",
  "What scares you about the future?",
  "What excites you about the future?",
  "What do you think our relationship does best?",
  // Ridiculous Scenarios (186-195)
  "If we had to survive a zombie apocalypse, who would last longer?",
  "What reality show would we dominate?",
  "If our life were a sitcom, what would the show be called?",
  "If we swapped lives for a day, what would be the hardest part for you?",
  "If we had a theme song that played every time we entered a room, what would it be?",
  "If we were cartoon characters, what would we look like?",
  "If we had to start a weird business together, what would it be?",
  "If we were criminals, what crime would we be best at?",
  "If we were in a heist movie, what would each of our roles be?",
  "If aliens landed tomorrow, what would we do first?",
  // Which One of Us? (196-205)
  "Which one of us would survive longest in the wilderness?",
  "Which one of us would get arrested first?",
  "Which one of us would win a reality cooking show?",
  "Which one of us would forget our kid at the grocery store?",
  "Which one of us would accidentally become famous?",
  "Which one of us would be the worst spy?",
  "Which one of us would go viral for something embarrassing?",
  "Which one of us would most likely start a cult?",
  "Which one of us would win a stand-up comedy contest?",
  "Which one of us would handle being stranded on an island better?",
  // Ridiculous Choices (206-215)
  "Would you rather fight one horse-sized duck or 100 duck-sized horses?",
  "Would you rather never eat dessert again or never eat pizza again?",
  "Would you rather always have to sing instead of talk or dance instead of walk?",
  "Would you rather be famous for something stupid or unknown for something amazing?",
  "Would you rather live in a treehouse or a castle?",
  "Would you rather only watch one movie forever or one TV show forever?",
  "Would you rather have a rewind button or a pause button for life?",
  "Would you rather only eat breakfast foods forever or dinner foods forever?",
  "Would you rather be able to talk to animals or speak every language?",
  "Would you rather always be 10 minutes early or 20 minutes late?",
  // Funny Personal Questions (216-225)
  "What's the most ridiculous outfit you've ever worn?",
  "What's the weirdest job you could imagine me having?",
  "What's the most embarrassing thing that happened to you as a kid?",
  "What food combination do you secretly love but shouldn't?",
  "What's a hill you will irrationally die on?",
  "What's something you believed as a kid that was totally wrong?",
  "What's a useless talent you have?",
  "What's a completely pointless thing you're weirdly proud of?",
  "What's something that instantly makes you laugh?",
  "What's a random thing that annoys you way more than it should?",
  // About Each Other (226-235)
  "What's my funniest habit?",
  "What's the most 'me' thing I do?",
  "What's something weird we do as a couple?",
  "What's a phrase I say all the time?",
  "What's something we'd probably get famous for as a couple?",
  "What's the dumbest argument we've ever had?",
  "What's a moment where we looked ridiculous together?",
  "What's a personality trait we both share that causes chaos?",
  "What's something people would be surprised to learn about us?",
  "If our family had a mascot, what would it be?",
  // Close the Day (236-245)
  "What was today's highlight?",
  "What are you grateful for about today?",
  "What would make tomorrow great?",
  "Is there anything you want to let go of from today?",
  "What are you looking forward to tomorrow?",
  "What's one thing we did well today?",
  "What made you feel loved today?",
  "What's one intention for tomorrow?",
  "What do you want to dream about tonight?",
  "What's one thing you want me to know before we sleep?",
];
